name: Build Windows yuv.dll

on:
  push:
    paths:
      - ".github/workflows/build-windows-libyuv-dll.yml"
  workflow_dispatch:
    inputs:
      ref:
        description: "libyuv ref (branch, tag or commit). Leave empty for default."
        required: false
        default: ""

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build-libyuv-dll:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Developer Command Prompt for Microsoft Visual C++
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set up latest CMake
        uses: jwlawson/actions-setup-cmake@802fa1a2c4e212495c05bf94dba2704a92a472be # v2.0.2
        with:
          cmake-version: "latest"

      - name: Set up ninja
        uses: seanmiddleditch/gha-setup-ninja@8b297075da4cd2a5f1fd21fe011b499edf06e9d2 # v4

      - name: Clone libyuv
        shell: pwsh
        run: |
          $Ref = '${{ github.event.inputs.ref }}'
          if ([string]::IsNullOrEmpty($Ref)) {
            git clone --single-branch https://chromium.googlesource.com/libyuv/libyuv
          } else {
            git clone --single-branch https://chromium.googlesource.com/libyuv/libyuv
            cd libyuv
            git fetch origin $Ref --depth 1
            git checkout FETCH_HEAD
            cd ..
          }

      - name: Configure (CMake, Ninja, clang-cl, shared)
        run: >
          cmake -G Ninja -S libyuv -B libyuv/build
          -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -DCMAKE_POSITION_INDEPENDENT_CODE=ON
        env:
          CC: clang-cl
          CXX: clang-cl

      - name: Build
        run: cmake --build libyuv/build --config Release --target yuv --parallel
        env:
          CC: clang-cl
          CXX: clang-cl

      - name: Upload yuv.dll artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libyuv-windows-x64-msvc
          if-no-files-found: error
          path: |
            libyuv/build/*.dll
            libyuv/build/*.lib
            libyuv/include/**
            libyuv/build/*.pdb